### ISSUE TITLE
Generators

### ISSUE THREAD

**Issue by victorlcampos** [britton-jb/sentinel#1]
Hi guys,
I'm working in generators for guardian(https://github.com/victorlcampos/gen_guardian) and I think we can  work together to make the amazing guardian lib, better.

**Comment by britton-jb** [comment]
Hey Victor. We should definitely work together on this one. I like your use of code generation by the way.

What kind of things were you thinking of adding to Guardian to improve it?

Right now I want to modify Sentinel as it is currently to utilize Ueberauth, to make it easy to use social authentication as well as the currently enabled email and password authentication. From there I was thinking add a mix task to churn out most of the setup.

I was also thinking that adding the [devise-lockable](http://www.rubydoc.info/github/plataformatec/devise/master/Devise/Models/Lockable) or [devise-trackable](http://www.rubydoc.info/github/plataformatec/devise/master/Devise/Models/Trackable) functionality could be really helpful for a lot of people.

**Comment by victorlcampos** [comment]
For now I'm working to have a generator template for email/password model like devise has. I think it's a important think for use the lib.

I'm very new in Elixir, so if you could give me some insights for how improve the generator solution. I will appretiated.

And if you like it i could send pr for merge to projects

**Comment by britton-jb** [comment]
Yeah, I think the email/password model is a great start.

I think merging these projects would be great. How are you thinking we should do that?

**Comment by victorlcampos** [comment]
I can fork this project and send PR.

**Comment by britton-jb** [comment]
Sounds great.
