### ISSUE TITLE
Lockable and example app

### ISSUE THREAD

**Issue by kathgironpe** [britton-jb/sentinel#13]
Hi!
I'm reviewing this for a project. I wonder if you already have an example app done.

Maybe I could help with that. I don't know if this is what I need yet, or whether will work with what I have already done. It's a Phoenix app with React.js front-end. 

Currently, there are features here that I don't need and it's missing what I need: #9  Lockable. 

I have not looked into how this was done in Devise, but I guess you need  `failed_attempts` and `locked_at` fields

https://github.com/katgironpe/rails_api_template/blob/master/db/schema.rb

**Comment by britton-jb** [comment]
@katgironpe - no example app currently. I'd really appreciate you creating one though, although I understand if you need to wait for me to implement lockable first.

Without digging too much into the details I can't imagine why this wouldn't work with your Phoenix/React combo. I've been using it personally as a Phoenix/Vue.js app up to this point. It is worth noting that this isn't a port of Devise, so the database isn't going to match up exactly.

I haven't looked into what else, if anything, would be needed to implement lockable (#9) yet. Right now my next focus will be on adding Ueberauth functionality, which would be an Omniauth equivalent in Rails-land. Based on what I believe the lockable module in Devise includes I don't believe that it would be a huge amount of effort, but it would be a good sized contribution.

**Comment by kathgironpe** [comment]
@britton-jb I would try to work on it this week.

**Comment by britton-jb** [comment]
That will be great. Let me know if you need anything.
