### ISSUE TITLE
UserView Layouts

### ISSUE THREAD

**Issue by Draiken** [britton-jb/sentinel#16]
Hi there!

More of a question than an issue, but exhausted my google searches trying to find a solution and you may know this already.

I provide a `Phoenix.View` object on Sentinel's configuration. It works finding the template, but I could not find a way to add my application layout to it.
Since normally the controller adds the layout, and the controller is on Sentinel, not my application, the only place I could add it is in the view.

My idea was to match the render method, add the layout and call upstream's render. Problem is, the layout key is not in the map.

```
def render("new.html", assigns), do: # add layout and call render again.
```

If I use the above, it's going to loop. My initial idea was to pattern match when the key is NOT there, but either I'm bad at google or there isn't a way to do that.

The second option, to render the template myself, also doesn't work since the render method is the last one in the public API of phoenix's view.

My last instinct was to just "override" the controller method. That would mean I'd need to have the Sentinel controller as a behavior that I could override the methods myself. Using that I'm guessing the layout will already be set by `use App.Web, :controller`. But this is coming from someone with OO centric views, so this may be horrible or not even possible.

Would appreciate to hear any of your thoughts on this

Thanks!

**Comment by britton-jb** [comment]
Hey @Draiken, I had believed that was something overridable in the view, but upon looking this morning I'm not able to find that. Right now the best suggestion I have is that you can override it in the router using a plug and the following syntax: `plug :put_layout, {MayApp.LayoutView, :whatever_the_layout_is_named}`.

It looks like this is a new feature that I'll have to implement.

**Comment by britton-jb** [comment]
Implemented this in the v2 branch, documentation in the README.
