### ISSUE TITLE
Separate User & Auth models / tables

### ISSUE THREAD

**Issue by ghost** [britton-jb/sentinel#23]
This is a design suggestion.

When you store everything in one table it will work, but its not extendable for further scenarios.
I would suggest to create a separate auth table and a separate user table.

Pros:
1. An user is able to use multiple auth strategies. like facebook / google / email / others..
2. The user model does not depend on a authentication strategy 
3. Clean separation, cleaner models

**Comment by britton-jb** [comment]
I completely agree. In fact all of this is actually in progress with my v2 update, which will include ueberuath for oauth/multiple auth strategies out of the box, and removes the user model auth strategy dependence. To be honest v1 was premature and not something I'm proud of really.

**Comment by britton-jb** [comment]
Separated the user and ueberauth models in the v2 branch, which should have a 2.0.0 release shortly.
