### ISSUE TITLE
UserView documentation.

### ISSUE THREAD

**Issue by sgeos** [britton-jb/sentinel#24]
The documentation example settings list `user_view: MyApp.UserModel.View,`.  I had to change this to `user_view: MyApp.UserView,` to get Sentinel to work.

**Comment by britton-jb** [comment]
Sorry about that. Thanks for filing the issue. 
1.0.0 has a number of issues that I'm working through for a v2 release.

**Comment by britton-jb** [comment]
Updated view handling and documentation in upcoming v2 release, available as the the v2 branch here on Github.
