### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by auser** [britton-jb/sentinel#25]
I'd love to contribute to this project. Is it still in active development?

**Comment by britton-jb** [comment]
Yes, but it's very slow to be updated because I have a day job and other hobbies. I've got a v2 branch that I'm working on that refactors a lot of the code base, and should be mostly complete on the JSON side. Currently working on refactoring HTML side.

**Comment by britton-jb** [comment]
I pushed the branch that I've been working on for a while, `v2`. It keeps the same spirit while changing some of the implementation a bit. It should be in a place where the specs for the JSON side are all green, and seem to behave as expected/desired. 

The HTML side Is currently being worked through as I said, but if you'd like to help me with that, or have other feature ideas you'd like to see I'd love the hand. I know I'm not able to get as much done on this as would be good for the Elixir community.

**Comment by sahrizvi** [comment]
Hello Britton, 
Thanks a lot creating this! This is a huge help for SPA like projects which are not using HTML capabilities of Phoenix and need to have a user identity management workflow. 
I do realize from comments that you are busy with work and leisure, and yet I see that the v2 branch is gearing up for rc1. Just wanted to let you know that I really appreciate your effort.

**Comment by britton-jb** [comment]
@sahrizvi I appreciate the feedback. Yeah, right now I've got all of the code and specs essentially where I want them on the v2 branch, so I'm now going to begin some actual use testing with some of my own projects. So far I've ran into a few bugs that need specs and correction, but in not too long we should have 2.0.0.

**Comment by sahrizvi** [comment]
@britton-jb Great to know that. As for testing the v2, you can count me in, too. :-)
However, I'm using Ecto 2.1 and Bamboo 0.8. Would that be a problem? 
Below is the list of deps: 
```
     [{:phoenix, "~> 1.2.1"},
     {:phoenix_pubsub, "~> 1.0"},
     {:phoenix_ecto, "~> 3.2.1"},
     {:postgrex, ">= 0.0.0"},
     {:guardian, "~> 0.13.0"},
     {:comeonin, "~> 2.5.3"},
     {:plug, "~> 1.0"},
     {:httpoison, "~> 0.10.0"},
     {:bamboo, "~> 0.8"},
     {:bamboo_smtp, "~> 1.3"},
     {:sentinel, github: "britton-jb/sentinel", branch:"v2"}]
```

**Comment by britton-jb** [comment]
I can't say for sure offhand, but I'll take a look.

**Comment by sahrizvi** [comment]
I understand. I'll go with the above anyway, and report back with the outcome. Thanks!

**Comment by britton-jb** [comment]
Should have 2.0.0 released by next Monday, assuming everything goes according to plan.

**Comment by sahrizvi** [comment]
Yay!!!  🍻 🎉  🎉  🎉  🎉 🍻

**Comment by tierralibre** [comment]
Thank you!
