### ISSUE TITLE
2.0.0rc

### ISSUE THREAD

**Issue by britton-jb** [britton-jb/sentinel#27]
Currently testing HTML and JSON for the 2.0.0rc, available here as the v2 branch.

Fixed issue with improper session verification using Guardian plugs in most recent commit. Working through ensuring there are no other issues.

Given the way it looks to be performing we should have a 2.0.0 official release by next Monday.

**Comment by britton-jb** [comment]
New issue in the RC with the HTML password reset request form, working to resolve.

**Comment by britton-jb** [comment]
Wrapped up issue with password reset flow in latest commit, verifying the HTML flow for invitable and confirmable.

**Comment by britton-jb** [comment]
Verified HTML invitable flow and confirmable, including setting up a new email address.

**Comment by britton-jb** [comment]
Published 2.0.0 this morning in Hex.

**Comment by tierralibre** [comment]
Thank you!

I will be testing it this week in an app!

**Comment by britton-jb** [comment]
@tierralibre if you run into any problems don't hesitate to submit to submit an issue.
