### ISSUE TITLE
When running mix sentinel.install

### ISSUE THREAD

**Issue by tierralibre** [britton-jb/sentinel#28]
When running mix sentinel.install mix shows the following error:

* (File.Error) could not stream "deps/sentinel/test/support/migrations/guardian_db_migration.exs": no such file or directory
    (elixir) lib/file/stream.ex:78: anonymous fn/2 in Enumerable.File.Stream.reduce/3
    (elixir) lib/stream.ex:1240: anonymous fn/5 in Stream.resource/3
    (elixir) lib/enum.ex:1767: Enum.map/2
    lib/mix/tasks/install.ex:111: Mix.Tasks.Sentinel.Install.generate_token_migration/0
    lib/mix/tasks/install.ex:28: Mix.Tasks.Sentinel.Install.create_migrations/0
    lib/mix/tasks/install.ex:11: Mix.Tasks.Sentinel.Install.run/1
    (mix) lib/mix/task.ex:294: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
    (elixir) lib/code.ex:370: Code.require_file/2

When using github as the package source in mix deps it works fine.

**Comment by britton-jb** [comment]
Interesting. I'll get a fix for that up. Thank you.

**Comment by britton-jb** [comment]
Fixed this issue in 2.0.1 which I've released. Thanks for letting me know about this one.
