### ISSUE TITLE
example sentinel app

### ISSUE THREAD

**Issue by tierralibre** [britton-jb/sentinel#30]
Thank you for all this!

It would be great to have an example Sentinel 2.0 app.

Kind regards,

Angel

**Comment by britton-jb** [comment]
That's a great idea. I'll get that setup and link to it in the README

**Comment by tierralibre** [comment]
Thank you!

**Comment by britton-jb** [comment]
I've setup an [example app here](https://github.com/britton-jb/sentinel_example), and linked to it in the README.

**Comment by tierralibre** [comment]
Thank you!
