### ISSUE TITLE
Ueberauth

### ISSUE THREAD

**Issue by britton-jb** [britton-jb/sentinel#5]
On the back burner until I wrap up the HTML views, but I'd like to add ueberauth functionality out of the box as well.

**Comment by deini** [comment]
This would be the dream

**Comment by britton-jb** [comment]
I appreciate the feedback.

Right now I don't have the roadmap clearly explained, but I'm currently
wrapping up v1 which should be a decent code base refactor, along with
adding HTML views, and a few other nice things. V2 which will follow after
will include this. I'm hoping it won't be too long, but could be a month or
so before I get to that point.

**Comment by sgeos** [comment]
I thing out of the box Ueberauth integration would be fantastic.

**Comment by britton-jb** [comment]
2.0.0 is currently being tested and should be released by Monday, which includes Ueberauth integration out of the box.
